/* Generated By:JavaCC: Do not edit this line. ensamblerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ensamblerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMP = 5;
  /** RegularExpression Id. */
  int MOV = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int JMP = 8;
  /** RegularExpression Id. */
  int GET = 9;
  /** RegularExpression Id. */
  int PRINTR = 10;
  /** RegularExpression Id. */
  int PRINT = 11;
  /** RegularExpression Id. */
  int LD = 12;
  /** RegularExpression Id. */
  int LDI = 13;
  /** RegularExpression Id. */
  int FREE = 14;
  /** RegularExpression Id. */
  int RECURSO = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int HEX = 18;
  /** RegularExpression Id. */
  int BIN = 19;
  /** RegularExpression Id. */
  int FIN = 20;
  /** RegularExpression Id. */
  int COMA = 21;
  /** RegularExpression Id. */
  int DP = 22;
  /** RegularExpression Id. */
  int REG = 23;
  /** RegularExpression Id. */
  int VALOR = 24;
  /** RegularExpression Id. */
  int STR = 25;
  /** RegularExpression Id. */
  int ID = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"COMP\"",
    "\"MOV\"",
    "\"ADD\"",
    "\"JMP\"",
    "\"GET\"",
    "\"PRINTR\"",
    "\"PRINT\"",
    "\"LD\"",
    "\"LDV\"",
    "\"FREE\"",
    "<RECURSO>",
    "\"SUB\"",
    "\"MAIN\"",
    "<HEX>",
    "<BIN>",
    "\";\"",
    "\",\"",
    "\":\"",
    "<REG>",
    "<VALOR>",
    "<STR>",
    "<ID>",
  };

}
